Improve failed job error reporting
Resolves #2

The definition location of each job defined, is kept in Kitto.Runner
to provide information helpful for debugging.

`Code.load_file/1` is used to load job files instead of `Code.eval_file/1` and
now proper stacktrace info indicating the original location of the erroring code
is emitted.

Before
------

```
16:15:06.596 [error] Process #PID<0.1727.0> raised an exception
** (RuntimeError) Boom Shakalaka
    (kitto) lib/kitto/stats_server.ex:66: Kitto.StatsServer.measure_func/2
    (kitto) lib/kitto/job.ex:35: Kitto.Job.with_interval/1
```

After
-----

```
15:58:27.230 [error] Process #PID<0.1442.0> raised an exception
** (Kitto.Job.Error) Job :buzzwords failed to run.
Defined in: jobs/buzzwords.ex:3:
Error: ** (RuntimeError) Boom Shakalaka
Stacktrace:     jobs/buzzwords.ex:10: anonymous fn/0 in :elixir_compiler_29.__FILE__/1
(stdlib) timer.erl:166: :timer.tc/1
  (kitto) lib/kitto/stats_server.ex:73: Kitto.StatsServer.timed_call/1
  (kitto) lib/kitto/stats_server.ex:46: Kitto.StatsServer.measure_call/1
  (kitto) lib/kitto/job.ex:35: Kitto.Job.with_interval/1
```